from utils import DictAttr

nao_configs_dict = {
        'data_dir': 'data/penn/',
        'model_dir': 'nao_search_exp',# os.path.join(args.model_dir, 'child'),
        'child_arch_pool': None,
        'child_emb_size': 850,
        'child_nhid': 850,
        'child_nhidlast': 850,
        'child_lr': 0.25,
        'child_clip': 10,
        'child_train_epochs': 1000,
        'child_eval_every_epochs': 200,
        'child_batch_size': 256,
        'child_eval_batch_size': 256,
        'child_bptt': 35,
        'child_dropout': 0.75,
        'child_dropouth': 0.25,
        'child_dropoutx': 0.75,
        'child_dropouti': 0.2,
        'child_dropoute': 0.0,
        'child_drop_path': 0.0,
        'save': 'EXP',
        'seed': 1267,
        'nonmono': 5,
        'child_log_interval': 50,
        'child_alpha': 0.0,
        'child_beta': 1e-3,
        'child_weight_decay': 5e-7,
        'child_small_batch_size': -1,
        'child_max_seq_len_delta': 20,
        'cuda': True,
        'single_gpu': True,
        'gpu': 0,
        'num_intermediate_nodes': 8,
        'num_operations': 4,
        'controller_shuffle': True,
        'controller_num_seed_arch': 1000,
        'controller_encoder_num_layers': 1,
        'controller_encoder_hidden_size': 96,
        'controller_encoder_emb_size': 48,
        'controller_mlp_num_layers': 4,
        'controller_mlp_hidden_size': 200,
        'controller_mlp_dropout': 0.0,
        'controller_decoder_num_layers': 1,
        'controller_decoder_hidden_size': 96,
        'controller_encoder_dropout': 0.1,
        'controller_decoder_dropout': 0.0,
        'controller_weight_decay': 1e-4,
        'controller_trade_off': 0.8,
        'controller_train_epochs': 1000,
        'controller_save_frequency': 1,
        'controller_batch_size': 100,
        'controller_lr': 0.001,
        'controller_optimizer': 'adam',
        'controller_max_gradient_norm': 5.0,
        'controller_predict_beam_width': 0,
        'controller_predict_lambda': 1,
        'controller_max_step_size': 30,
        'controller_max_new_archs': 300,
        'main_path': None,
        'top_archs': None,
        'random_new_archs': None,
        'use_avg_leaf': False,
        'handle_hidden_mode': None,
        'emulate_ws_solutions': None
}

nao_configs = DictAttr(nao_configs_dict)
