apiVersion: batch/v1
kind: Job
metadata:
  name: kyu-automl-darts-eval-seed-1267-original
spec:
  activeDeadlineSeconds: 345600 # 4-days
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 168151
        fsGroup: 11166
      containers:
      - name: pytorch-automl-framework
        image: ic-registry.epfl.ch/mlo/automl_cuda9
        command: ['python3.6', 'train.py']
        workingDir: /home/kyu/.pycharm/darts/rnn/
        env:
        - name: ROLE
          value: worker
        - name: HOME
          value: /home/kyu
        - name: PYTHONPATH
          value: /home/kyu/.pycharm/search_space_framework:/home/kyu/.pycharm/darts/rnn
        resources:
          limits:
            nvidia.com/gpu: 1 # requests one GPU
            memory: 12Gi
          requests:
            memory: 12Gi
        volumeMounts:
        # mount the data volumes
        - mountPath: /home/kyu
          name: cvlabdata2
          subPath: home/kyu
        - mountPath: /cvlabdata2
          name: cvlabdata2
      volumes:
#      - name: mlo-scratch
#        persistentVolumeClaim:
#          claimName: mlo-scratch
      - name: cvlabdata2
        persistentVolumeClaim:
          claimName: pv-cvlabdata2
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 8Gi
---
